STRINGS = {
    "en": {
        "browse_catalog": "Browse Catalog",
        "feedback": "Feedback",
        "help": "Help",
        "hello_message": "Hey there! 👋\n\nI'm your friendly online-shop bot. Here are some commands to get you started\n\n/help - Get assistance and see what I can do.\n/info - Learn more about this bot.\n/catalog - Browse out product catalog.",
        "help_message": "Here are some commands to get you started:\n\n/start - Start interaction with the bot.\n/help - Get assistance and see what I can do.\n/info - Learn more about this bot.\n/catalog - Browse out product catalog.",
        "language_btn": "Language 🇺🇦/🇬🇧",
        "choose_language": "Choose your language:",
        "language_changed": "Language changed to English",
        "admin_feedbacks": "Feedbacks",
        "catalog_intro": "Here is our product catalog. Browse through our selection of amazing products!\n\nTotal products available: {total_count}.\n\nGood luck! 🎉",
        "catalog_more": "Here are more products from our catalog! Enjoy browsing! 🎉",
        "invalid_product_id": "Invalid product ID.",
        "product_not_found": "Product not found.",
        "product_details": "Product Details:\n\nName: {name}\nDescription: {description}\nPrice: {price} {currency}",
        "no_description": "No description available.",
        "error_username_required": "You need a username to place orders.",
        "order_created": "Order Created Successfully! 🎉\n\nOrder ID: {order_id}\nStatus: {status}\nPrice: {price} {currency}\n\nPlease complete the payment using the button below. 👇",
        "error_payment": "Error creating payment: {error}",
        "btn_buy": "Buy 🛒",
        "btn_next": "Next ▶️",
        "btn_pay_now": "Pay Now 💳",
        "btn_i_have_paid": "I have paid ✅",
        "enter_feedback": "Please enter your feedback about our bot:",
        "feedback_sent": "Thank you for your feedback! It has been sent to our admins.",
        "order_not_found": "Order not found.",
        "order_already_paid": "Order is already paid! ✅",
        "no_payment_info": "No payment info found for this order.",
        "payment_successful": "Payment successful! ✅",
        "payment_received": "Payment received for Order #{order_id}! Thank you! 🎉\nWe will process it shortly.",
        "payment_status": "Payment status: {status}. Please complete payment.",
        "error_check_payment": "Error checking payment status.",
        "view_pending_orders": "View Pending Orders",
        "btn_approve": "Approve ✅",
        "btn_cancel": "Cancel ❌",
        "btn_yes_remove": "Yes, Remove",
        "btn_no_cancel": "No, Cancel",
        "btn_prev": "⬅️ Prev",
        "btn_back_to_list": "Back to List",
    },
    "uk": {
        "browse_catalog": "Переглянути каталог",
        "feedback": "Відгук",
        "help": "Допомога",
        "hello_message": "Привіт! 👋\n\nЯ твій дружній бот онлайн-магазину. Ось кілька команд для початку:\n\n/help - Отримати допомогу та дізнатися, що я можу робити.\n/info - Дізнатися більше про цього бота.\n/catalog - Переглянути наш каталог товарів.",
        "help_message": "Ось кілька команд для початку:\n\n/start - Почати взаємодію з ботом.\n/help - Отримати допомогу та дізнатися, що я можу робити.\n/info - Дізнатися більше про цього бота.\n/catalog - Переглянути наш каталог товарів.",
        "language_btn": "Мова 🇺🇦/🇬🇧",
        "choose_language": "Оберіть вашу мову:",
        "language_changed": "Мову змінено на Українську",
        "admin_feedbacks": "Відгуки",
        "catalog_intro": "Ось наш каталог товарів. Перегляньте наш вибір чудових товарів!\n\nВсього товарів: {total_count}.\n\nУспіхів! 🎉",
        "catalog_more": "Ось ще товари з нашого каталогу! Приємного перегляду! 🎉",
        "invalid_product_id": "Невірний ID товару.",
        "product_not_found": "Товар не знайдено.",
        "product_details": "Деталі товару:\n\nНазва: {name}\nОпис: {description}\nЦіна: {price} {currency}",
        "no_description": "Опис відсутній.",
        "error_username_required": "Вам потрібно мати ім'я користувача, щоб робити замовлення.",
        "order_created": "Замовлення створено успішно! 🎉\n\nID замовлення: {order_id}\nСтатус: {status}\nЦіна: {price} {currency}\n\nБудь ласка, оплатіть замовлення, використовуючи кнопку нижче. 👇",
        "error_payment": "Помилка створення платежу: {error}",
        "btn_buy": "Купити 🛒",
        "btn_next": "Далі ▶️",
        "btn_pay_now": "Оплатити зараз 💳",
        "btn_i_have_paid": "Я оплатив ✅",
        "enter_feedback": "Будь ласка, введіть ваш відгук про нашого бота:",
        "feedback_sent": "Дякуємо за ваш відгук! Його було надіслано нашим адміністраторам.",
        "order_not_found": "Замовлення не знайдено.",
        "order_already_paid": "Замовлення вже оплачено! ✅",
        "no_payment_info": "Інформацію про оплату не знайдено.",
        "payment_successful": "Оплата успішна! ✅",
        "payment_received": "Оплату отримано для Замовлення #{order_id}! Дякуємо! 🎉\nМи скоро його обробимо.",
        "payment_status": "Статус оплати: {status}. Будь ласка, завершіть оплату.",
        "error_check_payment": "Помилка перевірки статусу оплати.",
        "view_pending_orders": "Переглянути очікуючі замовлення",
        "btn_approve": "Підтвердити ✅",
        "btn_cancel": "Скасувати ❌",
        "btn_yes_remove": "Так, видалити",
        "btn_no_cancel": "Ні, скасувати",
        "btn_prev": "⬅️ Назад",
        "btn_back_to_list": "Назад до списку",
    },
}


def get_string(key: str, lang_code: str = "en") -> str:
    """
    Get a localized string for the given key and language code.
    Falls back to 'en' if the language or key is not found.
    """
    lang_strings = STRINGS.get(lang_code, STRINGS["en"])
    return lang_strings.get(key, STRINGS["en"].get(key, key))
