CREATE TABLE IF NOT EXISTS user_feedbacks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  feedback TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
