INSERT INTO products (name, description, price, currency, image_url) VALUES
('🥐 Croissant', 'Flaky, buttery, Paris-level smug.', 2.5, 'UAH', 'https://picsum.photos/seed/croissant/200/200'),
('☕ Coffee', 'Liquid sanity.', 1.2, 'UAH', 'https://picsum.photos/seed/coffee/200/200'),
('🥯 Bagel', 'Bread with commitment issues.', 1.8, 'UAH', 'https://picsum.photos/seed/bagel/200/200'),
('🍵 Tea', 'Elegant leaf juice.', 1.0, 'UAH', 'https://picsum.photos/seed/tea/200/200'),
('🍰 Chocolate Cake', 'Mood booster + sugar tax combo.', 3.6, 'UAH', 'https://picsum.photos/seed/cake/200/200'),
('🥪 Sandwich', 'Bread. Stuff. Bread again.', 4.5, 'UAH', 'https://picsum.photos/seed/sandwich/200/200'),
('🍊 Orange Juice', 'Sunshine in a cup.', 2.0, 'UAH', 'https://picsum.photos/seed/oj/200/200'),
('⚡ Espresso', 'One shot, straight to the brain.', 1.4, 'UAH', 'https://picsum.photos/seed/espresso/200/200'),
('🥛 Latte', 'Coffee''s introverted cousin.', 2.8, 'UAH', 'https://picsum.photos/seed/latte/200/200'),
('💧 Americano', 'Watered-down ambition.', 2.0, 'UAH', 'https://picsum.photos/seed/americano/200/200'),
('🫧 Cappuccino', 'Caffeine under a foam hat.', 2.6, 'UAH', 'https://picsum.photos/seed/cappuccino/200/200'),
('🍫 Hot Chocolate', 'Warm hug for the soul.', 2.7, 'UAH', 'https://picsum.photos/seed/hotchoc/200/200'),
('🧁 Muffin', 'Cupcake without the costume.', 1.9, 'UAH', 'https://picsum.photos/seed/muffin/200/200'),
('🍩 Donut', 'Fried joy wheel.', 1.7, 'UAH', 'https://picsum.photos/seed/donut/200/200'),
('💧 Water', 'Aquatic substance. Surprisingly relevant for survival.', 0.9, 'UAH', 'https://picsum.photos/seed/water/200/200'),
('🧊 Iced Coffee', 'Cold brew for emotionally distant people.', 2.3, 'UAH', 'https://picsum.photos/seed/icedcoffee/200/200'),
('🍓 Fruit Salad', 'Virtue bowl.', 3.2, 'UAH', 'https://picsum.photos/seed/fruitsalad/200/200'),
('🍮 Cheesecake', 'Soft, sweet, existential.', 3.9, 'UAH', 'https://picsum.photos/seed/cheesecake/200/200'),
('🥑 Avocado Toast', 'Millennial luxury item.', 5.2, 'UAH', 'https://picsum.photos/seed/avocado/200/200'),
('🏋️ Energy Bar', 'Pretends to be healthy. Actually candy.', 1.5, 'UAH', 'https://picsum.photos/seed/energy/200/200');
